spring:
  profiles:
    active: dev


  jpa:
    open-in-view: true #web请求下的懒加载问题
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
    properties:
      hibernate:
   #     format_sql: true
        enable_lazy_load_no_trans: true  #非web请求下的懒加载问题解决
